version: "3.1"

services:
  postgresDev:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: games_dev
    ports:
      - "3002:5432"
  postgresTest:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: games_test
    ports:
      - "3003:5432"
